### ISSUE TITLE
五一过了你在重写吗？？

### ISSUE THREAD

**Issue by ppbibo** [jeffzh3ng/fuxi#11]
五一过了你在重写吗？？

**Comment by jeffzh3ng** [comment]
离五一还有351天，不着急

**Comment by xirotech** [comment]
说点有用的吧 去年底测试发现的问题贴这里

Port Scanner因为是调用Nmap 所以完全没问题，但没有历史任务结果留存，切换页面就看不见了

资产发现功能正常，但不清楚周期扫描间隔是多久，开了一台虚拟机等了1小时未见新增进资产列表，第二天才看到

漏洞扫描/子域名扫描  功能效率低下，后台可见fuxi_scanner.py多个进程，CPU有时负载或满载，但长久未见结果,且系统内存整体占用在3.53G左右，最终测试下来功能确实可用，可发现漏洞，可扫描子域名，但时间太久了，与其他扫描器相比效率低下，疑似扫描机制存在问题

认证测试  这个功能如果设置单一目标单一协议 就很快扫完 ，结果正确，但如果指定多协议C段扫描 就特别慢 ，结果无效 ，且其任务列表中的 Target Info按钮功能无效，完全无用 

执行任务过程中 ，切换主监控状态面板特别慢

**Comment by Leezj9671** [comment]
端午过去了……

**Comment by shyixiu** [comment]
还有1个半月就中秋了😄

**Comment by samshuai** [comment]
2020了

**Comment by jeffzh3ng** [comment]
现在是2020年3月，hoover2015 提出的问题均已修复，该 issus 将关闭
